---
title: "gt table: mean test scores by state"
description: |
author:
  - name: Rebecca Gordon
date: 2022-03-09
output:
  distill::distill_article:
    self_contained: false
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval = TRUE,
                      message = FALSE,
                      warning = FALSE)


library(edld652)
library(tidyverse)
library(here)
library(janitor)
library(skimr)
library(rio)
#install.packages("fuzzyjoin")
library(fuzzyjoin)
library(viridis)
library(patchwork)
library(albersusa)
library(ggridges)
#install.packages("biscale")
library(biscale)
#install.packages("cowplot")
library(cowplot)
library(grid)
#install.packages("gridtext")
library(gridtext)
#install.packages("usmap")
library(usmap)
library(colorblindr)
library(gt)
library(scales)
library(reactable)
```

```{r load-datasets, echo=FALSE}

mathsch_10 <- get_data("EDFacts_math_achievement_sch_2010_2019")

rlasch_10 <- get_data("EDFacts_rla_achievement_sch_2010_2019")
```


#### Rebecca
**Research Question:** 

How do high school students’ subgroup makeup (i.e., Race/ethnicity, Male vs. Female, economically disadvantaged, Limited English, Migrant status, Disability status, and Homelessness) differ among states/regions? 


```{r rebecca-datawrangling, echo=FALSE}

df <- full_join(mathsch_10, rlasch_10) 

df2 <- df %>% 
	mutate(ECDmath = gsub("[^0-9.-]", "", ECD_MTHHSPCTPROF),
				 ECDrla = gsub("[^0-9.-]", "", ECD_RLAHSPCTPROF),
				 LEPrla = gsub("[^0-9.-]", "", LEP_RLAHSPCTPROF),
				 LEPmath = gsub("[^0-9.-]", "", LEP_MTHHSPCTPROF),
				 HOMmath = gsub("[^0-9.-]", "", HOM_MTHHSPCTPROF),
				 HOMrla = gsub("[^0-9.-]", "", HOM_RLAHSPCTPROF),
				 Mmath = gsub("[^0-9.-]", "", M_MTHHSPCTPROF),
				 Mrla = gsub("[^0-9.-]", "", M_RLAHSPCTPROF),
				 Fmath = gsub("[^0-9.-]", "", F_MTHHSPCTPROF),
				 Frla = gsub("[^0-9.-]", "", F_RLAHSPCTPROF),
				 MBLmath = gsub("[^0-9.-]", "", MBL_MTHHSPCTPROF),
				 MBLrla = gsub("[^0-9.-]", "", MBL_RLAHSPCTPROF),
				 MHImath = gsub("[^0-9.-]", "", MHI_MTHHSPCTPROF),
				 MHIrla = gsub("[^0-9.-]", "", MHI_RLAHSPCTPROF),
				 MWHmath = gsub("[^0-9.-]", "", MWH_MTHHSPCTPROF),
				 MWHrla = gsub("[^0-9.-]", "", MWH_RLAHSPCTPROF),
				 CWDmath = gsub("[^0-9.-]", "", CWD_MTHHSPCTPROF),
				 CWDrla = gsub("[^0-9.-]", "", CWD_RLAHSPCTPROF))

df2$ECDmath = readr::parse_number(df2$ECDmath) 
df2$ECDrla = readr::parse_number(df2$ECDrla) 
df2$LEPrla = readr::parse_number(df2$LEPrla) 
df2$LEPmath = readr::parse_number(df2$LEPmath) 
df2$HOMrla = readr::parse_number(df2$HOMrla) 
df2$HOMmath = readr::parse_number(df2$HOMmath) 
df2$Mrla = readr::parse_number(df2$Mrla) 
df2$Mmath = readr::parse_number(df2$Mmath) 
df2$Frla = readr::parse_number(df2$Frla) 
df2$Fmath = readr::parse_number(df2$Fmath) 
df2$MBLrla = readr::parse_number(df2$MBLrla) 
df2$MBLmath = readr::parse_number(df2$MBLmath) 
df2$MHIrla = readr::parse_number(df2$MHIrla) 
df2$MHImath = readr::parse_number(df2$MHImath) 
df2$MWHmath = readr::parse_number(df2$MWHmath) 
df2$MWHrla = readr::parse_number(df2$MWHrla) 
df2$CWDmath = readr::parse_number(df2$CWDmath) 
df2$CWDrla = readr::parse_number(df2$CWDrla) 

dat <- df2 %>% 
	group_by(STNAM) %>% 
	summarise(
		mean_EconomicallyDisadvantaged_math = mean(ECDmath, na.rm = TRUE),
		mean_EconomicallyDisadvantaged_reading = mean(ECDrla, na.rm = TRUE),
		mean_EnglishLearner_math = mean(LEPmath, na.rm = TRUE),
		mean_EnglishLearner_reading = mean(LEPrla, na.rm = TRUE),
		mean_Homeless_math = mean(HOMmath, na.rm = TRUE),
		mean_Homeless_reading = mean(HOMrla, na.rm = TRUE),
		mean_Male_math = mean(Mmath, na.rm = TRUE),
		mean_Male_reading = mean(Mrla, na.rm = TRUE),
		mean_Female_math = mean(Fmath, na.rm = TRUE),
		mean_Female_reading = mean(Frla, na.rm = TRUE),
		mean_Black_math = mean(MBLmath, na.rm = TRUE),
		mean_Black_reading = mean(MBLrla, na.rm = TRUE),
		mean_Hispanic_math = mean(MHImath, na.rm = TRUE),
		mean_Hispanic_reading = mean(MHIrla, na.rm = TRUE),
		mean_White_math = mean(MWHmath, na.rm = TRUE),
		mean_White_reading = mean(MWHrla, na.rm = TRUE),
		mean_Disabled_math = mean(CWDmath, na.rm = TRUE),
		mean_Disabled_reading = mean(CWDrla, na.rm = TRUE)
	) 

dat <- dat %>% filter(!STNAM == "BUREAU OF INDIAN AFFAIRS" & !STNAM == "stnam" & !STNAM == "PUERTO RICO") 

regions <- import(here("data","us_census_bureau_regions_and_divisions.csv")) %>%
	rename(state = `State Code`, `STNAM` = State)

df_regions <- regex_inner_join(dat, regions, ignore_case = TRUE)


df_pivot <- df_regions %>% 
	pivot_longer(
		cols = starts_with("mean_"),
		names_to = c("Subgroup", "test"),
		values_to = "mean_pct",
		names_sep = "_",
		values_drop_na = TRUE,
		names_repair = "check_unique",
		names_prefix = "mean_"
	) 

df_pivot$STNAM.y[c(863:879)] <- "West Virginia"
df_pivot$state[c(863:879)] <- "WV"

df_pivot<- df_pivot %>% 
  slice(-c(303:320))

#There were 2 West Virginias and Kansases

df_pivot$STNAM.y <- as.factor(df_pivot$STNAM.y)
df_pivot$Subgroup <- as.factor(df_pivot$Subgroup)

```
```{r panelset, echo=FALSE}
xaringanExtra::use_panelset()
```
::::: {.panelset}

::: {.panel}

## Table {.panel-name}

```{r rebecca-table, echo=FALSE}
min_pct <- min(df_pivot$mean_pct)
max_pct <- max(df_pivot$mean_pct)
pct_palette <- col_numeric(c("#FEF0D9", "#990000"), domain = c(min_pct, max_pct), alpha = 0.75)

df_pivot %>%
  select(Subgroup, test, mean_pct, STNAM.y) %>% 
  group_by(STNAM.y, Subgroup)  %>%
  arrange(desc(mean_pct)) %>% 
  gt() %>% 
  tab_style(
    style = list(
      cell_fill("black"),
      cell_text(color = "white", weight = "bold")
      ),
    locations = cells_row_groups()
  ) %>% 
  tab_style(
    style = cell_text(color = "darkgrey", weight = "bold"),
    locations = cells_stub()
  ) %>% 
     cols_label(mean_pct = md("**Mean Percent at or above proficient**"), test = md("**Test by state**")) %>%
  data_color(columns = vars(mean_pct),
               colors = pct_palette) %>% 
  opt_table_lines("none") 

```

:::

::: {.panel}

## Prior version {.panel-name}
```{r rebecca-table-prior, echo=FALSE}
min_pct <- min(df_pivot$mean_pct)
max_pct <- max(df_pivot$mean_pct)
pct_palette <- col_numeric(c("#FEF0D9", "#990000"), domain = c(min_pct, max_pct), alpha = 0.75)

df_pivot %>%
  select(Subgroup, test, mean_pct, STNAM.y) %>% 
  group_by(STNAM.y)  %>%
  arrange(desc(mean_pct)) %>% 
  gt() %>% 
     cols_label(mean_pct = "Mean Percent at or above proficient") %>%
	data_color(columns = vars(mean_pct),
               colors = pct_palette)

```

:::

::: {.panel}

## Code {.panel-name}

```{r rebecca-table-code, results='hide'}
min_pct <- min(df_pivot$mean_pct)
max_pct <- max(df_pivot$mean_pct)
pct_palette <- col_numeric(c("#FEF0D9", "#990000"), domain = c(min_pct, max_pct), alpha = 0.75)

df_pivot %>%
  select(Subgroup, test, mean_pct, STNAM.y) %>% 
  group_by(STNAM.y)  %>%
  arrange(desc(mean_pct)) %>% 
  gt() %>% 
     cols_label(mean_pct = "Mean Percent at or above proficient") %>% 
  data_color(columns = vars(mean_pct),
               colors = pct_palette)

```
:::

:::::

